# Generated by Django 4.2.7 on 2024-04-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_registeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
